%YAML:1.0 # need to specify the file type at the top!

cam:
  enabled: true
  max_n: 2
  use_stereo: true
  stereo_pair: [0, 1]
  do_calib_ext: true  # Keep this true if you need external calibration
  do_calib_int: true  # Keep internal calibration enabled
  do_calib_dt: true
  n_pts: 60  # Reduce if calibration is too slow; consider 500 for faster performance
  fast: 60  # Lower the threshold to 40 to detect more features
  grid_x: 10
  grid_y: 10
  min_px_dist: 15  # Increase this to reduce the number of nearby features
  knn: 0.7  # Lower the KNN ratio for stricter feature matching
  downsample: true  # Enable downsampling to improve processing speed
  histogram_method: "CLAHE"  # NONE, HISTOGRAM, CLAHE
  max_slam: 100
  max_msckf: 200  # Increase the number of features for MSCKF to improve accuracy
  feat_rep: "GLOBAL_3D"
  init_cov_dt: 1e-1  # Slightly increase the covariance for timing to handle potential drift
  init_cov_ex_o: 1e-1  # Same for orientation
  init_cov_ex_p: 1e-1  # Increase for position to account for motion variations
  init_cov_in_k: 1e-0  # Reduce the covariance for camera intrinsics for more confidence
  init_cov_in_c: 1e-0  # Adjust intrinsic calibration covariance
  init_cov_in_r: 1e-0  # Lower to handle rotational bias more effectively
  sigma_px: 2  # Decrease pixel noise for sharper feature detection
  chi2_mult: 0.9  # Adjust chi-squared multiplier for slightly looser outlier rejection

  # Feature-related settings
  fi_min_dist: 20.0  # Increase the minimum feature distance for more robust matching
  fi_max_dist: 300  # Reduce the max feature distance to focus on closer features
  fi_max_baseline: 4500
  fi_max_cond_number: 200  # Lower condition number for stricter triangulation

# ==================================================================
# ==================================================================

cam0:
  timeoffset: 0.0001 # Slightly reduce the time offset for better synchronization
  T_imu_cam:
    - [-0.004319018701418653, -0.9999885992544466, -0.0020365261075575075, 0.04851846641062367]
    - [0.9999904276147462, -0.004320435379673804, 0.0006917492372857481, 0.011126438772353857]
    - [-0.0007005400302754278, -0.002033518935252497, 0.9999976870195282, -0.004624435602354069]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0785, -0.2383, 0, -0.0038]  # Leave as is unless re-calibrating
  distortion_model: radtan
  intrinsics: [401.71, 402.54, 326.12, 209.01]  # Check if recalibration is needed; keep these for now
  resolution: [640, 400]  # Keep resolution as is for performance reasons
  timeshift_cam_imu: 0.0001  # Reduce slightly for more precise synchronization
  topic: "/left/image_rect"

# Camera 1 configuration
cam1:
  timeoffset: 0.0001  # Align the time offset with camera 0
  T_imu_cam:
    - [-0.00437776749648483, -0.9999798283988005, -0.004601950374794038, -0.02719795162952729]
    - [0.9999903701524201, -0.004376304324740177, -0.00032796780790397394, 0.010906812321875035]
    - [0.00030782165694069564, -0.004603341825522695, 0.9999893571882976, -0.00327106466605724]
    - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
    - [0.9999967075349849, -6.05607568951949e-05, -0.0025653950132786462, -0.07572744797327788]
    - [5.7945236684360325e-05, 0.9999994785278975, -0.0010196010357917595, -0.00022714714170129767]
    - [0.0025654554233071874, 0.0010194490263697917, 0.999996189573812, 0.0012175385152692077]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0444, -0.1335, 0, -0.0015]  # Keep as is unless re-calibrating
  distortion_model: radtan
  intrinsics: [402.88, 404.02, 327.13, 209.14]  # Same as above for camera 1
  resolution: [640, 400]
  timeshift_cam_imu: 0.0001  # Match time offset with camera 0
  topic: "/right/image_rect"
